### ISSUE TITLE
[CIS Azure] Logging and Monitoring rules

### ISSUE THREAD

**Issue by jeniawhite** [elastic/cloudbeat#1256]
We would like to implement the following rules:
- [ ] 5.5 Ensure that SKU Basic/Consumption is not used on artifacts that need to be monitored (Particularly for Production Workloads)
- [ ] 5.2.1 Ensure that Activity Log Alert exists for Create Policy Assignment
- [x] 5.2.10 Ensure that Activity Log Alert exists for Delete Public IP Address rule
- [x] 5.2.2 Ensure that Activity Log Alert exists for Delete Policy Assignment
- [x] 5.2.3 Ensure that Activity Log Alert exists for Create or Update Network Security Group
- [x] 5.2.4 Ensure that Activity Log Alert exists for Delete Network Security Group
- [x] 5.2.5 Ensure that Activity Log Alert exists for Create or Update Security Solution
- [x] 5.2.6 Ensure that Activity Log Alert exists for Delete Security Solution
- [x] 5.2.7 Ensure that Activity Log Alert exists for Create or Update SQL Server Firewall Rule
- [x] 5.2.8 Ensure that Activity Log Alert exists for Delete SQL Server Firewall Rule
- [x] 5.2.9 Ensure that Activity Log Alert exists for Create or Update Public IP Address rule

**Comment by orestisfl** [comment]
## 5.5 verification failed :x:

No finding for this rule
![image](https://github.com/elastic/cloudbeat/assets/5778622/c1e90fc6-49f3-41f1-b495-7c1370d5c6ca)

**Comment by orestisfl** [comment]
## 5.2.1 verification failed :x:
![image](https://github.com/elastic/cloudbeat/assets/5778622/ae013e44-4a25-4d9e-80be-adb830ee1ed5)

According to the description, there should be one finding, either positive or negative regarding the rule where condition is ```
Whenever the Activity Log has an event with
Category='Administrative', Signal name='Create policy assignment
(policyAssignments)
```

**Comment by jeniawhite** [comment]
5.5 - SKU property wasn't mapped, resolved in [Azure add mapping for SKU property #1468](https://github.com/elastic/cloudbeat/pull/1468)

**Comment by jeniawhite** [comment]
Activity log alert rules had a problem because we sent them both as a batch and as single resources.
- #1476 

Removed the single resource sending and I've left the batch only
This is a screenshot of 5.1.2 evaluated correctly
![Screenshot 2023-10-25 at 15 42 03](https://github.com/elastic/cloudbeat/assets/12246907/4e454bed-1f4e-424b-9a42-04f4c1a00a04)

This PR will fix the scenario when the user doesn't have any rules and we still want to evaluate rules as failure due to that.
- https://github.com/elastic/cloudbeat/pull/1475

**Comment by orestisfl** [comment]
@kfirpeled please re-verify with the new fix. Ideally, check 5.5 and all 5.2.x rules, at minimum check 5.5 and 5.2.1.

**Comment by animehart** [comment]
- 5.5 rules is not showing up on Findings
- 5.2.x is also not showing up, but this is due to the fix to add alerts logs is not added on this BC, thus it is expected. Discussed this with @jeniawhite

**Comment by animehart** [comment]
Rule

- 5.2.4
- 5.2.5
- 5.2.6
Still fails even after I added activity log rules on Azure for it 
<img width="1470" alt="Screenshot 2023-10-31 at 1 41 52 AM" src="https://github.com/elastic/cloudbeat/assets/8703149/f3d42939-9268-4680-a319-1d819b4978d3">

**Comment by kfirpeled** [comment]
thanks @animehart 

@oren-zohar / @jeniawhite would you prefer that we will keep this ticket open? or close it, and open tickets for the bugs found?

**Comment by oren-zohar** [comment]
@kfirpeled close and open a ticket for problematic rules please
