### ISSUE TITLE
[BUG] Kibana - Findings flyout - some references links are broken

### ISSUE THREAD

**Issue by kfirpeled** [elastic/cloudbeat#97]
**Describe the bug**

When testing some of the links in the rule `references` (under `General` tab), they reference to pages that are no longer exists.

**Preconditions**
Kibana environment with csp plugin enabled
Agent installed that generates findings

**To Reproduce**

1. Open findings for rule `Ensure that the --profiling argument is set to false (Automated)`
2. Click on `https://github.com/kubernetes/community/blob/master/contributors/devel/profiling.md`

**Expected behavior**
Opened page should be existing

**Screenshots 📸**

![Screen Shot 2022-05-09 at 21 44 15](https://user-images.githubusercontent.com/61654899/167476455-fe84ca05-d525-409e-ae5a-4f3f4013ce69.png)

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Kibana Version: COMMIT: [df225b213b188c81888141cee2ec191424fc0649](https://github.com/elastic/kibana/commits/df225b213b188c81888141cee2ec191424fc0649)
 - Endpoint Version:
 - Other Version: 
   - Cloudbeat Version: COMMIT [7e1f1a135fbb3459151232dda34531527291776e](https://github.com/elastic/cloudbeat/commits/7e1f1a135fbb3459151232dda34531527291776e)

**Additional context**

**Comment by kfirpeled** [comment]
Suggesting to check all references we have in [csp-security-policies](https://github.com/elastic/csp-security-policies) repo and validate them

**Comment by oren-zohar** [comment]
still a few broken links:
- `Ensure that the --client-ca-file argument is set as appropriate (Automated)` - https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/
- `Ensure that the --client-ca-file argument is set as appropriate (Automated)` - https://rootsquash.com/securing-the-kubernetes-api/
- `Ensure that the --profiling argument is set to false (Automated)` - https://github.com/kubernetes/community/blob/master/contributors/devel/profiling.md
- `Ensure that the --profiling argument is set to false (Automated)` - https://github.com/kubernetes/community/blob/master/contributors/devel/profiling.md
- `Ensure that the --profiling argument is set to false (Automated)` - https://github.com/kubernetes/community/blob/master/contributors/devel/profiling.md
- `Ensure that the --rotate-certificates argument is not set to false (Manual)
` - https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#kubelet-configuration
- `Ensure that the --rotate-certificates argument is not set to false (Manual)
` - https://kubernetes.io/docs/imported/release/notes/
- `Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate (Automated)` - https://rootsquash.com/securing-the-kubernetes-api/
- `Ensure that the Kubelet only makes use of Strong CryptographicCiphers (Manual)` - **References section is empty**
- `Minimize the admission of containers with added capabilities (Automated)` - https://www.nccgroup.trust/uk/our-research/abusing-privileged-and-unprivileged-linux-containers/ **(redirects to another place)**
- `Minimize the admission of containers with capabilities assigned (Manual)` - bad copy?
<img width="570" alt="image" src="https://user-images.githubusercontent.com/85433724/172797410-ec4d34e0-a8f8-4895-b63b-cca75d1ad992.png">
- `Minimize wildcard use in Roles and ClusterRoles (Manual)` - **References section is empty**
-

**Comment by kfirpeled** [comment]
I think this is the doc on github
https://github.com/kubernetes/community/blob/master/contributors/devel/profiling.md --> 
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scalability/profiling.md

**Comment by tinnytintin10** [comment]
this is an issue we should take up with the CIS organization - it's not something we should take care of. I will bring this up with Tricia. 

@amitkanfer can you implement a crawler that checks to see if the links are broken?

**Comment by amitkanfer** [comment]
will get fixed in the new rules generator. closing this issue.

**Comment by gurevichdmitry** [comment]
@tehilashn, is there a task for new rules generator? Can we link it here and label this bug as verified?

**Comment by amitkanfer** [comment]
@gurevichdmitry here's the relevant function that checks for the broken links:
https://github.com/elastic/cis_policies_generator/blob/main/src/index.ts#L33

this repo will probably find a new home soon... /cc @jeniawhite

**Comment by tehilashn** [comment]
Reopening it - the tool exists but the problem was not solved. will get done as part of 8.5

**Comment by oren-zohar** [comment]
Will be closed by the following:
- https://github.com/elastic/csp-security-policies/pull/119
- https://github.com/elastic/security-team/issues/4478
Closing @tehilashn

**Comment by tehilashn** [comment]
@oren-zohar - when are we going to run this tool and update the the actual template?

**Comment by oren-zohar** [comment]
next sprint @tehilashn
